[package]
name = "thunder-daw"
version = "0.2.4"
edition = "2024"
description = "A small FL Studio-style DAW in Rust"
authors = ["thunder-daw contributors"]
license = "MIT"
repository = "https://github.com/canureal/thunder-daw"
homepage = "https://canureal.github.io/thunder-daw/"

[package.metadata.wix]
upgrade-guid = "9B538FC9-5CB1-4E8A-84BD-695D60CEB5E7"
path-guid = "42412B8A-3916-4C6A-ACB7-0F30D645728D"
license = false
eula = false

[dependencies]
cpal = "0.18"
eframe = "0.36"
egui = "0.36"
fundsp = "0.23"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hound = "3"
dirs = "6"

[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.dist]
cargo-dist-version = "0.32.0"
allow-dirty = ["msi"]
rust-version = "1.99.0"
ci = ["github"]
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
]
installers = ["shell", "powershell", "msi", "homebrew"]
install-success-msg = "thunder-daw is installed! Run it with: thunder-daw"
tap = "canureal/homebrew-tap"
include = ["assets/thunder-daw.desktop", "assets/icon.svg"]
publish-jobs = ["homebrew"]

[workspace.metadata.dist.dependencies.apt]
libasound2-dev = "*"
libx11-dev = "*"
libxcb1-dev = "*"
libxext-dev = "*"
libxrandr-dev = "*"
libxi-dev = "*"
libxcursor-dev = "*"
libxinerama-dev = "*"
libxkbcommon-dev = "*"
libxkbcommon-x11-dev = "*"
libwayland-dev = "*"
libegl-dev = "*"
libgl-dev = "*"
libdbus-1-dev = "*"
